Name:           ros-kinetic-costmap-prohibition-layer
Version:        0.0.5
Release:        0%{?dist}
Summary:        ROS costmap_prohibition_layer package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-costmap-2d
Requires:       ros-kinetic-dynamic-reconfigure
Requires:       ros-kinetic-roscpp
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-costmap-2d
BuildRequires:  ros-kinetic-dynamic-reconfigure
BuildRequires:  ros-kinetic-roscpp

%description
ROS-Package that implements a costmap layer to add prohibited areas to the
costmap-2D by a user configuration.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Jan 25 2017 Stephan Kurzawe <stephan.kurzawe@tu-dortmund.de> - 0.0.5-0
- Autogenerated by Bloom

* Sun Oct 30 2016 Stephan Kurzawe <stephan.kurzawe@tu-dortmund.de> - 0.0.4-0
- Autogenerated by Bloom

* Fri Oct 28 2016 Stephan Kurzawe <stephan.kurzawe@tu-dortmund.de> - 0.0.3-0
- Autogenerated by Bloom

* Thu Oct 27 2016 Stephan Kurzawe <stephan.kurzawe@tu-dortmund.de> - 0.0.2-0
- Autogenerated by Bloom

